### ISSUE TITLE
Exception when running basic example on videos

### ISSUE THREAD

**Issue by Spock112** [Kitware/SMQTK#260]
Hello,

when I'm trying to run the example provided in http://smqtk.readthedocs.io/en/latest/webservices/iqrdemonstration.html on videos (I adapted the config json file) I end up with the following error message:

`Exception AttributeError: "'NoneType' object has no attribute 'free_index'" in <bound method FLANN.__del__ of <pyflann.index.FLANN instance at 0x7f339c9a2680>> ignored
Exception TypeError: 'must be type, not None' in  ignored`

The first exception is due to that it seems the flann class is sometimes no longer present when `__del__` is called in `TPL/flann-1.8.4/src/python/pyflann/index.py`

However I'm unable to determine the  origin of the second and final Exception.
Similar messages are reported when using `super`, however that's not my expertise.

I tried different types and sizes of videos even very tiny ones. I also manually set the use of compute cores to 1. It also didn't work. I'm running the latest master branch.

Please find the used config file attached.

Thank you in advance for your help.

Best regards,

[config.IqrSearchApp.video.json.txt](https://github.com/Kitware/SMQTK/files/383336/config.IqrSearchApp.video.json.txt)

**Comment by Purg** [comment]
Sadly, the support for video processing has fallen a little by the way-side as there have been a few non-trivial overhauls since its last use and recent projects have not desired video processing (theoretically, that could change in the near future, but we'll see). Additionally, the ColorDescriptor component hasn't been used in a while since our shift to using deep learning approaches (i.e. the caffe implementation, which does not have a video version [yet]).

Do you have a more complete log of what was run? Have you tried this using imagery? If so, does this same error occur (could tell us if its a general or content-type specific error)?

I'm decently sure that first error has to do with the ``ColorDescriptor_Base`` class (``<source>/python/smqtk/algorithms/descriptor_generator/colordescriptor/colordescriptor.py``), which uses pyflann (and thus the FLANN library) for bag-of-words.

The second error had no context, sadly. I usually only see those "... ignored" type errors at the end of execution due to python failing to cleanly destruct everything. Did this occur upon interpreter shutdown? Or during, and kicking out of, the middle of a run?
