### ISSUE TITLE
DataFileElement can be created with a non-existent file

### ISSUE THREAD

**Issue by danlamanna** [Kitware/SMQTK#293]
This seems counter intuitive, and isn't how `DataUrlElement` behaves with a URL that doesn't resolve.

Would it be a lot of work in the rest of SMQTK if this were to throw an exception upon a non existing file?

**Comment by Purg** [comment]
I don't think the ``DataFileElement`` being constructed with an invalid filepath is an issue (0 bytes). The fact that URL fails for invalid URLs might be the issue here.

In an internal branch (for public release at some point I hope) I have added more methods to the ``DataElement`` interface like ``set_bytes`` and ``is_read_only``, which adds more reason that elements, ones that are not perminently read-only anyway, can be constructed with then-non-existent URIs.

**Comment by Purg** [comment]
Said publicly released code added set methods to data elements.  File-based data elements will not write those bytes to disk (if it can).
