### ISSUE TITLE
DataFileElement should raise an exception if it can't guess a filetype

### ISSUE THREAD

**Issue by danlamanna** [Kitware/SMQTK#297]
Currently SMQTK tries to find the right content type via magic, defaulting to tika, and if neither are available it uses `mimetypes.guess_type` which can return `None`.

I think if it returns `None` an exception should be raised hinting at the user that they may need a file type detector installed (Tika or Magic).

**Comment by Purg** [comment]
On an internal branch that should be put up for public release one of these days is something that addresses that. Implicit action is removed from those classes and an additional constructor parameter for explicit content-type was added. I had originally left mimetypes able to be ``None`` because custom files could be used (binary files that don't adhere to a known type). Though, I suppose there is a mimetype for arbitrary binary, too...

**Comment by Purg** [comment]
file-magic and implicit badness resolve with merger of public release #322
